### ISSUE TITLE
Error: net::ERR_CONNECTION_REFUSED on yarn build

### ISSUE THREAD

**Issue by davidwieler** [manuelbieh/react-ssr-setup#26]
When running `yarn build`, I'm getting this error:
`UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_REFUSED at http://localhost:8505`

any idea what would cause this?

**Comment by davidwieler** [comment]
Nevermind, closing this.

I ripped out nodemon and replaced it with forever-monitor.

**Comment by manuelbieh** [comment]
Please check version 2.0.1. Has been merged an hour ago. This should fix it:
https://github.com/manuelbieh/react-ssr-setup/commit/87748a63cd3d1926e043ea7f2c75da73c9bcd5cb

**Comment by luiscvalmeida** [comment]
@manuelbieh nop, now I can't build at all with just by cloning the repository, installing dependencies as they are and running `yarn build`:
`Error: net::ERR_CONNECTION_REFUSED at http://localhost:8505`

**Comment by luiscvalmeida** [comment]
Thanks @manuelbieh , i'll look into that as well. Also I've noticed that running the start script but with production as the NODE_ENV doesn't generate the client build.

**Comment by manuelbieh** [comment]
The cause for this issue is that the server build is started in the build process to generate the static index.html but is then not properly terminated. So the Express server keeps running and, when you create another build, blocks the port.

**Comment by gswirrl** [comment]
Sorry still seeing this error in `657b4e1 `

Steps to reproduce:
1) clone repo
2) yarn install
3) yarn build

and the build fails with

```
Error: net::ERR_CONNECTION_REFUSED at http://localhost:8505
```

**Comment by manuelbieh** [comment]
Damn 😕

**Comment by manuelbieh** [comment]
Hm. Can't reproduce with a freshly cloned repo. Have you killed all possibly running node processes before pulling/cloning? 

I was able to create 5 consecutive builds without any issues.

**Comment by gswirrl** [comment]
doublechecking now.

**Comment by gswirrl** [comment]
By restarting my machine from scratch.... it ran first time, successfully. But. immediately doing `yarn build` a second time errors again

```
~/Desktop/react-ssr-setup-master $ yarn build
[...]
[2018-11-09T15:13:09.158Z] App is running: 🌎 http://localhost:8505
✨  Done in 17.91s.
~/Desktop/react-ssr-setup-master  $ yarn build
[...]
Error: net::ERR_CONNECTION_REFUSED at http://localhost:8505
```

Looking at my activity monitor i can't see any node processes still running at all.

**Comment by gswirrl** [comment]
(btw thank you so much - i know this must be a huge drag - i really appreciate the help)

**Comment by gswirrl** [comment]
> That's really annoying. 

Man! Im truly sorry. This is such a great project - you deserve better thanks than me whining! Sorry :coffee: 🌹 

osx 10.14 / node v11.0.0

fwiw doing `lsof -t -i :8505` returns empty and there arent any node processes running. could it be a timing thing?

**Comment by manuelbieh** [comment]
Will have to investigate further. Thanks for reporting!

Timing, possible but not very likely. Will try to reproduce it on my Mac with Node 11 soon.

**Comment by gswirrl** [comment]
Really very much appreciated. Thanks

**Comment by gswirrl** [comment]
Been looking at this some more over the weekend and have made some _nanoprogress_ :-)

If I add a simple wait in `build.js`, it seems to work consistently 

ie


```

function sleep(secs) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, (secs*1000));
}

[...]

script.on('start', async () => {
        try {
            sleep(2); // <-------- BODGE
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto(`http://localhost:${port}`);
            const pageContent = await page.content();
            fs.writeFileSync(`${paths.clientBuild}/index.html`, pageContent);
            await browser.close();
            script.emit('quit');
        } catch (err) {
            script.emit('quit');
            console.log(err);
        }
    });

```

**Comment by manuelbieh** [comment]
Weird 🤔 I will have a look at it! Thanks a lot!

**Comment by manuelbieh** [comment]
A colleague of mine told me the same. If that reliably solves this issue I will add it. Maybe my machine is just too fast (i7 HQ-series with 32 gigs of RAM ;)).

Could you do me one more favor and check how low you can set the delay while still being able to create 5 consecutive builds without having that error? I don't want to increase the build time unnecessarily. Thanks!

**Comment by gswirrl** [comment]
It's a total bodge but ¯\_(ツ)_/¯ 

On my feeble MacBook, I get slightly inconsistent results, so it's hard to make it more fine-grained -`sleep(0.2)` seems to work consistently, and `sleep(0.1)` fails often. 

`sleep(0.15)` again seems to work... reliably...??? (i just ran 20 consecutive builds). But the reported build times varied between 9.34 and 11.81s so it all seems a bit concerning! :-)

**Comment by gswirrl** [comment]
> My assumption is that the puppeteer process tries to access the server before the server has properly started.

Definitely agree

> subscribe to events to start puppeteer

That sounds like a much, MUCH better idea than waiting and hoping! Though I guess if there's no convenient hook, it might not be crazy to try to access the server, then if that fails, wait and retry, then wait longer and rety etc??

So many thanks again.

**Comment by GAjay** [comment]
if i comment the lines my production build is running perfectly.    
```
//await browser.close();
            //script.emit('quit');
```
